import type { TestItem } from '../types'

/**
 * IPIP Big-Five Factor Markers (50 items, Goldberg 1992).
 * English items: public domain. Source: https://ipip.ori.org/newBigFive5broadKey.htm
 * Korean: 저자 번역 (preliminary, 심리측정 타당화 미완료).
 *
 * Scoring direction: items are coded from the perspective of their factor.
 * reverseScored=true means high Likert response indicates LOW factor score.
 * Example: "I am relaxed most of the time" is reverse for Neuroticism.
 */
export const IPIP50_ITEMS: TestItem[] = [
  {
    id: 'ipip50-1',
    order: 1,
    textEn: 'I am the life of the party.',
    textKo: '나는 모임에서 분위기를 띄우는 사람이다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-2',
    order: 2,
    textEn: 'I feel little concern for others.',
    textKo: '나는 다른 사람에게 별로 관심이 없다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-3',
    order: 3,
    textEn: 'I am always prepared.',
    textKo: '나는 항상 준비가 되어 있다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-4',
    order: 4,
    textEn: 'I get stressed out easily.',
    textKo: '나는 쉽게 스트레스를 받는다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-5',
    order: 5,
    textEn: 'I have a rich vocabulary.',
    textKo: '나는 어휘력이 풍부하다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-6',
    order: 6,
    textEn: "I don't talk a lot.",
    textKo: '나는 말수가 적은 편이다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-7',
    order: 7,
    textEn: 'I am interested in people.',
    textKo: '나는 사람들에게 관심이 많다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-8',
    order: 8,
    textEn: 'I leave my belongings around.',
    textKo: '나는 물건을 아무데나 놓아두는 편이다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-9',
    order: 9,
    textEn: 'I am relaxed most of the time.',
    textKo: '나는 대부분 편안한 상태이다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-10',
    order: 10,
    textEn: 'I have difficulty understanding abstract ideas.',
    textKo: '나는 추상적인 개념을 이해하기 어렵다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-11',
    order: 11,
    textEn: 'I feel comfortable around people.',
    textKo: '나는 사람들과 있을 때 편안함을 느낀다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-12',
    order: 12,
    textEn: 'I insult people.',
    textKo: '나는 다른 사람에게 모욕적인 말을 하는 편이다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-13',
    order: 13,
    textEn: 'I pay attention to details.',
    textKo: '나는 세부사항에 주의를 기울인다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-14',
    order: 14,
    textEn: 'I worry about things.',
    textKo: '나는 이것저것 자주 걱정한다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-15',
    order: 15,
    textEn: 'I have a vivid imagination.',
    textKo: '나는 상상력이 풍부하다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-16',
    order: 16,
    textEn: 'I keep in the background.',
    textKo: '나는 눈에 띄지 않게 있는 편이다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-17',
    order: 17,
    textEn: "I sympathize with others' feelings.",
    textKo: '나는 다른 사람의 감정에 공감한다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-18',
    order: 18,
    textEn: 'I make a mess of things.',
    textKo: '나는 일을 엉망으로 만드는 편이다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-19',
    order: 19,
    textEn: 'I seldom feel blue.',
    textKo: '나는 좀처럼 우울해하지 않는다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-20',
    order: 20,
    textEn: 'I am not interested in abstract ideas.',
    textKo: '나는 추상적인 생각에 관심이 없다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-21',
    order: 21,
    textEn: 'I start conversations.',
    textKo: '나는 먼저 대화를 시작한다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-22',
    order: 22,
    textEn: "I am not interested in other people's problems.",
    textKo: '나는 다른 사람의 문제에 관심이 없다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-23',
    order: 23,
    textEn: 'I get chores done right away.',
    textKo: '나는 해야 할 일을 바로 처리한다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-24',
    order: 24,
    textEn: 'I am easily disturbed.',
    textKo: '나는 쉽게 동요된다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-25',
    order: 25,
    textEn: 'I have excellent ideas.',
    textKo: '나는 훌륭한 아이디어를 잘 떠올린다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-26',
    order: 26,
    textEn: 'I have little to say.',
    textKo: '나는 할 말이 별로 없는 편이다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-27',
    order: 27,
    textEn: 'I have a soft heart.',
    textKo: '나는 마음이 여린 편이다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-28',
    order: 28,
    textEn: 'I often forget to put things back in their proper place.',
    textKo: '나는 물건을 제자리에 두는 것을 자주 잊는다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-29',
    order: 29,
    textEn: 'I get upset easily.',
    textKo: '나는 쉽게 속상해한다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-30',
    order: 30,
    textEn: 'I do not have a good imagination.',
    textKo: '나는 상상력이 풍부하지 않다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-31',
    order: 31,
    textEn: 'I talk to a lot of different people at parties.',
    textKo: '나는 파티에서 다양한 사람들과 대화를 나눈다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-32',
    order: 32,
    textEn: 'I am not really interested in others.',
    textKo: '나는 다른 사람들에게 별로 관심이 없다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-33',
    order: 33,
    textEn: 'I like order.',
    textKo: '나는 질서 있는 것을 좋아한다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-34',
    order: 34,
    textEn: 'I change my mood a lot.',
    textKo: '나는 기분이 자주 바뀐다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-35',
    order: 35,
    textEn: 'I am quick to understand things.',
    textKo: '나는 이해가 빠른 편이다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-36',
    order: 36,
    textEn: "I don't like to draw attention to myself.",
    textKo: '나는 주목받는 것을 좋아하지 않는다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-37',
    order: 37,
    textEn: 'I take time out for others.',
    textKo: '나는 다른 사람을 위해 시간을 내준다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-38',
    order: 38,
    textEn: 'I shirk my duties.',
    textKo: '나는 내 의무를 회피하는 편이다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-39',
    order: 39,
    textEn: 'I have frequent mood swings.',
    textKo: '나는 감정 기복이 심하다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-40',
    order: 40,
    textEn: 'I use difficult words.',
    textKo: '나는 어려운 단어를 즐겨 사용한다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-41',
    order: 41,
    textEn: "I don't mind being the center of attention.",
    textKo: '나는 주목받는 것을 꺼리지 않는다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-42',
    order: 42,
    textEn: "I feel others' emotions.",
    textKo: '나는 다른 사람의 감정을 잘 느낀다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-43',
    order: 43,
    textEn: 'I follow a schedule.',
    textKo: '나는 정해진 일정을 따르는 편이다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-44',
    order: 44,
    textEn: 'I get irritated easily.',
    textKo: '나는 쉽게 짜증을 낸다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-45',
    order: 45,
    textEn: 'I spend time reflecting on things.',
    textKo: '나는 여러 가지를 깊이 성찰하는 시간을 갖는다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-46',
    order: 46,
    textEn: 'I am quiet around strangers.',
    textKo: '나는 낯선 사람 앞에서는 조용한 편이다.',
    factor: 'extraversion',
    facet: 'extraversion',
    reverseScored: true,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-47',
    order: 47,
    textEn: 'I make people feel at ease.',
    textKo: '나는 다른 사람을 편안하게 해주는 편이다.',
    factor: 'agreeableness',
    facet: 'agreeableness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-48',
    order: 48,
    textEn: 'I am exacting in my work.',
    textKo: '나는 일할 때 꼼꼼하다.',
    factor: 'conscientiousness',
    facet: 'conscientiousness',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-49',
    order: 49,
    textEn: 'I often feel blue.',
    textKo: '나는 자주 우울함을 느낀다.',
    factor: 'neuroticism',
    facet: 'neuroticism',
    reverseScored: false,
    scaleType: 'likert5',
  },
  {
    id: 'ipip50-50',
    order: 50,
    textEn: 'I am full of ideas.',
    textKo: '나는 아이디어가 풍부하다.',
    factor: 'openness',
    facet: 'openness',
    reverseScored: false,
    scaleType: 'likert5',
  },
]
